### ISSUE TITLE
How to get definitions?

### ISSUE THREAD

**Issue by nudelmanaron** [SleepyBandit/oxford-dictionary#4]
Hey  Sleepy,

I am having issues on searching for definitions with the module.

When I use : 
var lookup = dict.definitions("programming");

  lookup.then(function(res) {
      console.log(res);
  },
  function(err) {
      console.log(err);
  });

In functon variable I receive:

{ metadata: { provider: 'Oxford University Press' },
  results:
   [ { id: 'programming',
       language: 'en',
       lexicalEntries: [Array],
       type: 'headword',
       word: 'programming' } ] }

So where are the definitions?

When I switch the method to .find, like this: 

var lookup = dict.find("programming");

I receive the same as the other method:

{ metadata: { provider: 'Oxford University Press' },
  results:
   [ { id: 'programming',
       language: 'en',
       lexicalEntries: [Array],
       type: 'headword',
       word: 'programming' } ] }

Can you help figure this out.
Thanks

**Comment by SleepyBandit** [comment]
If you look at your response you see the following line;
`"lexicalEntries: [Array]",`
this is where the data lives. I should update the README because in reality a basic console.log alone won't display the full object for the returned result. This is because it is a deep JSON structured object and console.log will only show a shallow representation of it.

To get the full result in a console.log(), you need to stringify it first. You can do that by replacing your console.log() with the following.
`console.log(JSON.stringify(res, null, 4));`
This should stringify your JSON object, allowing you to log the FULL result. Be prepared though, a lot may return in your console since you're logging the full object. The `4` represents the indentation you want to use, so change if you have a different preference.

You'll want to familiarize yourself with the general result structure because object dot notation will be important to surfacing the results you want to manipulate. The README file should show a full example of a return object to help as well.
